spring:
      datasource:
                 url: jdbc:mysql://localhost:3306/springsecurity
                 username: root
                 password:
      jpa:
           hibernate:
                     ddl-auto: create
           properties:
                      hibernate:
                                dialect: org.hibernate.dialect.MySQLDialect
                                format_sql: true

